// Generated by tools/gen-data.mjs from .team/ziiro-fleet/funnel. Do not edit by hand.
export const SEO_COPY = {
  "seo.home.title": "Your Business Spine: an AI plan in a minute",
  "seo.home.desc": "Answer a few questions and see which of the 33 agents in a full Business Spine your business needs today. ziiro AI is an AI consultancy based in India.",
  "seo.plan.title": "Your plan",
} as const;
