// Generated by tools/gen-data.mjs from .team/ziiro-fleet/funnel. Do not edit by hand.
export const SITE_COPY = {
  "nav.home.aria": "ziiro AI, home",
  "nav.mission": "Mission",
  "nav.who": "Who We Are",
  "nav.products": "Products",
  "nav.btn": "Book a call",
  "ph.nav.menu": "Menu",
} as const;
