// Generated by tools/gen-data.mjs from .team/ziiro-fleet/funnel. Do not edit by hand.

import type { Agent, DepartmentId } from "./contract.js";

export const AGENTS_VERSION = "2026-10-04";

export const DEPARTMENT_NAMES: Readonly<Record<DepartmentId, string>> = {
  "intelligence": "Intelligence",
  "marketing": "Marketing",
  "sales": "Sales",
  "deals": "Deals",
  "customer": "Customer",
  "operations": "Operations",
  "back-office": "Back Office"
};

export const AGENT_ROWS: readonly Agent[] = [
  {
    "id": "intelligence-markets",
    "number": 1,
    "department": "intelligence",
    "name": "Market researcher",
    "line": "Sizes up a market and checks what competitors charge.",
    "jobs": [
      {
        "id": "competitor-teardown",
        "name": "Competitor Teardown",
        "status": "mapped"
      },
      {
        "id": "pricing-research",
        "name": "Pricing Research",
        "status": "mapped"
      },
      {
        "id": "tam-market-sizing",
        "name": "TAM / Market Sizing",
        "status": "mapped"
      },
      {
        "id": "vertical-analysis",
        "name": "Vertical Analysis",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "intelligence-companies",
    "number": 2,
    "department": "intelligence",
    "name": "Company researcher",
    "line": "Finds out what a company does and who makes the call there, before you spend an hour on them.",
    "jobs": [
      {
        "id": "buying-committee-mapping",
        "name": "Buying-Committee Mapping",
        "status": "mapped"
      },
      {
        "id": "company-deep-dive",
        "name": "Company Deep-Dive",
        "status": "runs_on_our_company_today"
      },
      {
        "id": "funding-financials-lookup",
        "name": "Funding & Financials Lookup",
        "status": "mapped"
      },
      {
        "id": "tech-stack-detection",
        "name": "Tech-Stack Detection",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "intelligence-people",
    "number": 3,
    "department": "intelligence",
    "name": "People researcher",
    "line": "Tells you who someone is and who you both know.",
    "jobs": [
      {
        "id": "network-mapping",
        "name": "Network Mapping",
        "status": "mapped"
      },
      {
        "id": "person-research",
        "name": "Person Research",
        "status": "mapped"
      },
      {
        "id": "warm-path-finding",
        "name": "Warm-Path Finding",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "intelligence-monitoring",
    "number": 4,
    "department": "intelligence",
    "name": "News watcher",
    "line": "Keeps an eye on your clients and competitors, and tells you when something changes.",
    "jobs": [
      {
        "id": "account-monitoring",
        "name": "Account Monitoring",
        "status": "mapped"
      },
      {
        "id": "alert-routing",
        "name": "Alert Routing",
        "status": "mapped"
      },
      {
        "id": "news-mention-tracking",
        "name": "News & Mention Tracking",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "intelligence-synthesis",
    "number": 5,
    "department": "intelligence",
    "name": "Report writer",
    "line": "Turns the research into a short report you'll actually read, with the facts double-checked.",
    "jobs": [
      {
        "id": "adversarial-verification",
        "name": "Adversarial Verification",
        "status": "mapped"
      },
      {
        "id": "data-visualization",
        "name": "Data Visualization",
        "status": "mapped"
      },
      {
        "id": "research-reports",
        "name": "Research Reports",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "marketing-insights",
    "number": 6,
    "department": "marketing",
    "name": "Marketing analyst",
    "line": "Tells you which of your posts work and what your comments and DMs keep asking for.",
    "jobs": [
      {
        "id": "audience-analysis",
        "name": "Audience Analysis",
        "status": "mapped"
      },
      {
        "id": "competitor-analysis",
        "name": "Competitor Analysis",
        "status": "mapped"
      },
      {
        "id": "performance-mining",
        "name": "Performance Mining",
        "status": "mapped"
      },
      {
        "id": "trend-monitoring",
        "name": "Trend Monitoring",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "marketing-creation",
    "number": 7,
    "department": "marketing",
    "name": "Content maker",
    "line": "Writes the hooks and scripts, then makes the posts and ads.",
    "jobs": [
      {
        "id": "ad-creative",
        "name": "Ad Creative",
        "status": "mapped"
      },
      {
        "id": "caption-writing",
        "name": "Caption Writing",
        "status": "mapped"
      },
      {
        "id": "carousel-production",
        "name": "Carousel Production",
        "status": "mapped"
      },
      {
        "id": "deck-production",
        "name": "Deck Production",
        "status": "mapped"
      },
      {
        "id": "hook-writing",
        "name": "Hook Writing",
        "status": "runs_on_our_company_today"
      },
      {
        "id": "image-generation",
        "name": "Image Generation",
        "status": "mapped"
      },
      {
        "id": "landing-page-copy",
        "name": "Landing Page Copy",
        "status": "mapped"
      },
      {
        "id": "script-writing",
        "name": "Script Writing",
        "status": "mapped"
      },
      {
        "id": "thumbnail-cover-design",
        "name": "Thumbnail & Cover Design",
        "status": "mapped"
      },
      {
        "id": "video-production",
        "name": "Video Production",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "marketing-repurposing",
    "number": 8,
    "department": "marketing",
    "name": "Repurposer",
    "line": "Cuts one video into many clips, and turns what you know into something people swap their number for.",
    "jobs": [
      {
        "id": "clip-extraction",
        "name": "Clip Extraction",
        "status": "mapped"
      },
      {
        "id": "cross-platform-adaptation",
        "name": "Cross-Platform Adaptation",
        "status": "mapped"
      },
      {
        "id": "lead-magnet-builds",
        "name": "Lead-Magnet Builds",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "marketing-distribution",
    "number": 9,
    "department": "marketing",
    "name": "Publisher",
    "line": "Posts on time and keeps you showing up on Google and in AI answers.",
    "jobs": [
      {
        "id": "newsletter-broadcast",
        "name": "Newsletter & Broadcast",
        "status": "mapped"
      },
      {
        "id": "og-share-surface",
        "name": "OG & Share Surface",
        "status": "mapped"
      },
      {
        "id": "publishing",
        "name": "Publishing",
        "status": "mapped"
      },
      {
        "id": "seo-geo",
        "name": "SEO & GEO",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "marketing-brand-deals",
    "number": 10,
    "department": "marketing",
    "name": "Partnerships desk",
    "line": "Drafts the scripts and sign-off documents for brand collaborations.",
    "jobs": [
      {
        "id": "approval-docs",
        "name": "Approval Docs",
        "status": "mapped"
      },
      {
        "id": "deal-scripting",
        "name": "Deal Scripting",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "sales-targeting",
    "number": 11,
    "department": "sales",
    "name": "Ideal-client finder",
    "line": "Works out which businesses are worth chasing, and notices when one is ready to buy.",
    "jobs": [
      {
        "id": "icp-definition",
        "name": "ICP Definition",
        "status": "mapped"
      },
      {
        "id": "lookalike-modeling",
        "name": "Lookalike Modeling",
        "status": "mapped"
      },
      {
        "id": "market-mapping",
        "name": "Market Mapping",
        "status": "mapped"
      },
      {
        "id": "trigger-detection",
        "name": "Trigger Detection",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "sales-lead-sourcing",
    "number": 12,
    "department": "sales",
    "name": "List builder",
    "line": "Builds lists of real prospects from databases and maps, so you never hunt for them by hand.",
    "jobs": [
      {
        "id": "database-mining",
        "name": "Database Mining",
        "status": "mapped"
      },
      {
        "id": "list-building",
        "name": "List Building",
        "status": "runs_on_our_company_today"
      },
      {
        "id": "social-mining",
        "name": "Social Mining",
        "status": "mapped"
      },
      {
        "id": "web-maps-scraping",
        "name": "Web & Maps Scraping",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "sales-enrichment",
    "number": 13,
    "department": "sales",
    "name": "Contact checker",
    "line": "Finds the right number and email, and checks they work before anyone dials.",
    "jobs": [
      {
        "id": "account-enrichment",
        "name": "Account Enrichment",
        "status": "mapped"
      },
      {
        "id": "contact-enrichment",
        "name": "Contact Enrichment",
        "status": "mapped"
      },
      {
        "id": "email-verification",
        "name": "Email Verification",
        "status": "mapped"
      },
      {
        "id": "fit-scoring",
        "name": "Fit Scoring",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "sales-outreach-writing",
    "number": 14,
    "department": "sales",
    "name": "Outreach writer",
    "line": "Writes first messages that sound like you, for an email, a LinkedIn note or a call.",
    "jobs": [
      {
        "id": "cold-email-drafting",
        "name": "Cold Email Drafting",
        "status": "mapped"
      },
      {
        "id": "cold-call-scripting",
        "name": "Cold-Call Scripting",
        "status": "mapped"
      },
      {
        "id": "linkedin-messaging",
        "name": "LinkedIn Messaging",
        "status": "mapped"
      },
      {
        "id": "personalization-research",
        "name": "Personalization Research",
        "status": "mapped"
      },
      {
        "id": "proof-matching",
        "name": "Proof Matching",
        "status": "mapped"
      },
      {
        "id": "video-prospecting",
        "name": "Video Prospecting",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "sales-sequencing-send",
    "number": 15,
    "department": "sales",
    "name": "Campaign runner",
    "line": "Sends your outreach on schedule and keeps it out of spam folders.",
    "jobs": [
      {
        "id": "campaign-launch",
        "name": "Campaign Launch",
        "status": "mapped"
      },
      {
        "id": "campaign-orchestration",
        "name": "Campaign Orchestration",
        "status": "mapped"
      },
      {
        "id": "deliverability",
        "name": "Deliverability",
        "status": "mapped"
      },
      {
        "id": "send-optimization",
        "name": "Send Optimization",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "deals-inbound",
    "number": 16,
    "department": "deals",
    "name": "Enquiry responder",
    "line": "Answers every new enquiry within minutes and checks whether it's serious, so nobody goes cold waiting.",
    "jobs": [
      {
        "id": "comment-cta-fulfillment",
        "name": "Comment-CTA Fulfillment",
        "status": "mapped"
      },
      {
        "id": "inbox-triage",
        "name": "Inbox Triage",
        "status": "mapped"
      },
      {
        "id": "lead-qualification",
        "name": "Lead Qualification",
        "status": "we_build_it_for_you"
      },
      {
        "id": "speed-to-lead",
        "name": "Speed-to-Lead",
        "status": "we_build_it_for_you"
      }
    ]
  },
  {
    "id": "deals-reply-handling",
    "number": 17,
    "department": "deals",
    "name": "Reply sorter",
    "line": "Reads every reply, flags the serious ones and books the meeting.",
    "jobs": [
      {
        "id": "hot-lead-routing",
        "name": "Hot-Lead Routing",
        "status": "mapped"
      },
      {
        "id": "meeting-booking",
        "name": "Meeting Booking",
        "status": "runs_on_our_company_today"
      },
      {
        "id": "objection-response",
        "name": "Objection Response",
        "status": "mapped"
      },
      {
        "id": "referral-capture",
        "name": "Referral Capture",
        "status": "mapped"
      },
      {
        "id": "reply-classification",
        "name": "Reply Classification",
        "status": "runs_on_our_company_today"
      }
    ]
  },
  {
    "id": "deals-call-cycle",
    "number": 18,
    "department": "deals",
    "name": "Call companion",
    "line": "Preps you before a call, then turns it into notes and a follow-up you can send.",
    "jobs": [
      {
        "id": "call-capture",
        "name": "Call Capture",
        "status": "we_build_it_for_you"
      },
      {
        "id": "follow-up-drafting",
        "name": "Follow-Up Drafting",
        "status": "we_build_it_for_you"
      },
      {
        "id": "objection-library",
        "name": "Objection Library",
        "status": "mapped"
      },
      {
        "id": "post-call-debrief",
        "name": "Post-Call Debrief",
        "status": "runs_on_our_company_today"
      },
      {
        "id": "pre-call-briefing",
        "name": "Pre-Call Briefing",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "deals-deal-artifacts",
    "number": 19,
    "department": "deals",
    "name": "Proposal maker",
    "line": "Puts together quotes and proposals that look like yours.",
    "jobs": [
      {
        "id": "agreement-drafting",
        "name": "Agreement Drafting",
        "status": "mapped"
      },
      {
        "id": "deal-room-assembly",
        "name": "Deal Room Assembly",
        "status": "mapped"
      },
      {
        "id": "demo-prototyping",
        "name": "Demo Prototyping",
        "status": "mapped"
      },
      {
        "id": "pricing-support",
        "name": "Pricing Support",
        "status": "mapped"
      },
      {
        "id": "proposal-generation",
        "name": "Proposal Generation",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "deals-pipeline-ops",
    "number": 20,
    "department": "deals",
    "name": "Pipeline keeper",
    "line": "Shows where every deal stands and wakes up enquiries that went quiet.",
    "jobs": [
      {
        "id": "crm-hygiene",
        "name": "CRM Hygiene",
        "status": "mapped"
      },
      {
        "id": "forecasting",
        "name": "Forecasting",
        "status": "mapped"
      },
      {
        "id": "pipeline-reporting",
        "name": "Pipeline Reporting",
        "status": "mapped"
      },
      {
        "id": "reactivation",
        "name": "Reactivation",
        "status": "mapped"
      },
      {
        "id": "win-loss-analysis",
        "name": "Win/Loss Analysis",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "customer-support",
    "number": 21,
    "department": "customer",
    "name": "Support desk",
    "line": "Answers the questions you get every day and sends the angry ones straight to you.",
    "jobs": [
      {
        "id": "escalations",
        "name": "Escalations",
        "status": "mapped"
      },
      {
        "id": "faq-self-serve",
        "name": "FAQ & Self-Serve",
        "status": "mapped"
      },
      {
        "id": "macro-authoring",
        "name": "Macro Authoring",
        "status": "mapped"
      },
      {
        "id": "ticket-triage",
        "name": "Ticket Triage",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "customer-success",
    "number": 22,
    "department": "customer",
    "name": "Client care",
    "line": "Checks in on clients and spots the ones drifting away before they go.",
    "jobs": [
      {
        "id": "advocacy-referrals",
        "name": "Advocacy & Referrals",
        "status": "mapped"
      },
      {
        "id": "churn-prediction",
        "name": "Churn Prediction",
        "status": "mapped"
      },
      {
        "id": "health-scoring",
        "name": "Health Scoring",
        "status": "mapped"
      },
      {
        "id": "onboarding-journeys",
        "name": "Onboarding Journeys",
        "status": "mapped"
      },
      {
        "id": "qbr-prep",
        "name": "QBR Prep",
        "status": "mapped"
      },
      {
        "id": "renewals-expansion",
        "name": "Renewals & Expansion",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "customer-community",
    "number": 23,
    "department": "customer",
    "name": "Community manager",
    "line": "Replies to comments and keeps your group or page alive.",
    "jobs": [
      {
        "id": "engagement-replies",
        "name": "Engagement & Replies",
        "status": "mapped"
      },
      {
        "id": "event-coordination",
        "name": "Event Coordination",
        "status": "mapped"
      },
      {
        "id": "member-spotlights",
        "name": "Member Spotlights",
        "status": "mapped"
      },
      {
        "id": "moderation",
        "name": "Moderation",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "operations-onboarding",
    "number": 24,
    "department": "operations",
    "name": "Kickoff agent",
    "line": "Starts every new project the same way, with logins and folders ready on day one.",
    "jobs": [
      {
        "id": "access-collection",
        "name": "Access Collection",
        "status": "mapped"
      },
      {
        "id": "kickoff-pack",
        "name": "Kickoff Pack",
        "status": "mapped"
      },
      {
        "id": "project-scaffolding",
        "name": "Project Scaffolding",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "operations-build-ops",
    "number": 25,
    "department": "operations",
    "name": "Data mover",
    "line": "Pulls details out of documents and moves data between your tools, so your team stops copy-pasting.",
    "jobs": [
      {
        "id": "agent-evaluation",
        "name": "Agent Evaluation",
        "status": "mapped"
      },
      {
        "id": "data-migration",
        "name": "Data Migration",
        "status": "mapped"
      },
      {
        "id": "document-extraction",
        "name": "Document Extraction",
        "status": "we_build_it_for_you"
      },
      {
        "id": "integration-builds",
        "name": "Integration Builds",
        "status": "mapped"
      },
      {
        "id": "portal-provisioning",
        "name": "Portal Provisioning",
        "status": "mapped"
      },
      {
        "id": "qa-verification",
        "name": "QA & Verification",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "operations-client-comms",
    "number": 26,
    "department": "operations",
    "name": "Client updater",
    "line": "Sends progress updates and meeting notes, so clients don't have to ask.",
    "jobs": [
      {
        "id": "meeting-follow-ups",
        "name": "Meeting Follow-Ups",
        "status": "mapped"
      },
      {
        "id": "portal-sync",
        "name": "Portal Sync",
        "status": "mapped"
      },
      {
        "id": "status-updates",
        "name": "Status Updates",
        "status": "we_build_it_for_you"
      }
    ]
  },
  {
    "id": "operations-knowledge",
    "number": 27,
    "department": "operations",
    "name": "Memory keeper",
    "line": "Turns calls and finished work into notes and handover docs your team can use.",
    "jobs": [
      {
        "id": "context-maintenance",
        "name": "Context Maintenance",
        "status": "mapped"
      },
      {
        "id": "handoff-docs",
        "name": "Handoff Docs",
        "status": "mapped"
      },
      {
        "id": "sop-generation",
        "name": "SOP Generation",
        "status": "mapped"
      },
      {
        "id": "transcript-processing",
        "name": "Transcript Processing",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "operations-reliability",
    "number": 28,
    "department": "operations",
    "name": "Watchman",
    "line": "Watches your systems and running costs, and raises a flag when something breaks.",
    "jobs": [
      {
        "id": "cost-usage-tracking",
        "name": "Cost & Usage Tracking",
        "status": "mapped"
      },
      {
        "id": "incident-response",
        "name": "Incident Response",
        "status": "mapped"
      },
      {
        "id": "monitoring-alerting",
        "name": "Monitoring & Alerting",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "back-office-money-in",
    "number": 29,
    "department": "back-office",
    "name": "Collections agent",
    "line": "Sends invoices and politely chases whatever's still owed.",
    "jobs": [
      {
        "id": "collections",
        "name": "Collections",
        "status": "we_build_it_for_you"
      },
      {
        "id": "invoice-generation",
        "name": "Invoice Generation",
        "status": "mapped"
      },
      {
        "id": "payment-tracking",
        "name": "Payment Tracking",
        "status": "we_build_it_for_you"
      }
    ]
  },
  {
    "id": "back-office-finance-reporting",
    "number": 30,
    "department": "back-office",
    "name": "Numbers agent",
    "line": "Shows this month's revenue against your goal, and warns you before cash runs short.",
    "jobs": [
      {
        "id": "budget-tracking",
        "name": "Budget Tracking",
        "status": "mapped"
      },
      {
        "id": "cash-flow-forecasting",
        "name": "Cash-Flow Forecasting",
        "status": "mapped"
      },
      {
        "id": "goal-pacing",
        "name": "Goal Pacing",
        "status": "mapped"
      },
      {
        "id": "revenue-reporting",
        "name": "Revenue Reporting",
        "status": "we_build_it_for_you"
      }
    ]
  },
  {
    "id": "back-office-records",
    "number": 31,
    "department": "back-office",
    "name": "Records keeper",
    "line": "Files every document and contract where you can find it, and sorts expenses before your accountant asks.",
    "jobs": [
      {
        "id": "crm-sync",
        "name": "CRM Sync",
        "status": "mapped"
      },
      {
        "id": "contract-lifecycle",
        "name": "Contract Lifecycle",
        "status": "mapped"
      },
      {
        "id": "document-filing-retrieval",
        "name": "Document Filing & Retrieval",
        "status": "mapped"
      },
      {
        "id": "entity-compliance",
        "name": "Entity Compliance",
        "status": "mapped"
      },
      {
        "id": "expense-categorization",
        "name": "Expense Categorization",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "back-office-office",
    "number": 32,
    "department": "back-office",
    "name": "Office assistant",
    "line": "Keeps your calendar clean and your inbox sorted by what actually needs you.",
    "jobs": [
      {
        "id": "calendar-management",
        "name": "Calendar Management",
        "status": "mapped"
      },
      {
        "id": "email-triage",
        "name": "Email Triage",
        "status": "mapped"
      }
    ]
  },
  {
    "id": "back-office-talent",
    "number": 33,
    "department": "back-office",
    "name": "Hiring assistant",
    "line": "Finds and screens candidates, and helps new people settle in.",
    "jobs": [
      {
        "id": "candidate-sourcing",
        "name": "Candidate Sourcing",
        "status": "mapped"
      },
      {
        "id": "hr-policy-assistant",
        "name": "HR & Policy Assistant",
        "status": "mapped"
      },
      {
        "id": "onboarding-training",
        "name": "Onboarding & Training",
        "status": "mapped"
      },
      {
        "id": "screening-scheduling",
        "name": "Screening & Scheduling",
        "status": "mapped"
      }
    ]
  }
];
